input.onButtonPressed(Button.A, function () {
    music.playMelody("C5 B A G F E D C ", 120)
    basic.showNumber(1)
    music.playTone(131, music.beat(BeatFraction.Whole))
    basic.showNumber(2)
    music.ringTone(147)
    basic.showNumber(3)
    music.playTone(165, music.beat(BeatFraction.Whole))
    basic.showNumber(4)
    music.ringTone(175)
    basic.showNumber(5)
    music.ringTone(247)
    basic.showNumber(6)
    music.ringTone(262)
    basic.showNumber(7)
    music.ringTone(262)
    basic.showNumber(8)
    music.ringTone(262)
    basic.showNumber(9)
    music.rest(music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Heart)
    music.ringTone(659)
    basic.showIcon(IconNames.Yes)
    music.ringTone(659)
    basic.showIcon(IconNames.No)
    music.ringTone(698)
    basic.showIcon(IconNames.Happy)
    music.ringTone(784)
    basic.showIcon(IconNames.Confused)
    music.ringTone(880)
    basic.showIcon(IconNames.Angry)
    music.ringTone(784)
    basic.showIcon(IconNames.Sad)
    music.ringTone(698)
    basic.showIcon(IconNames.Asleep)
    music.ringTone(988)
    basic.showIcon(IconNames.Rollerskate)
    music.rest(music.beat(BeatFraction.Whole))
})
